### ISSUE TITLE
As a user, I want to see a waiting area after I have joined a game that is not yet ready to start in order to see how many players are missing or leave the game

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#10]
## Acceptance Criteria:
- [x] The waiting area includes the current number of players as well as a “Leave” button.
- [x] The number of players is always up-to-date
- [x] If the waiting area is left, the user is redirected to the lobby
- [x] If all users leave, the game will be deleted and will disappear from the lobby
- [x] As soon as the defined number of players have joined the game, the users will be redirected to the game view

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#13
- [x] sopra-fs22-group-14/CAHClient#14
- [x] sopra-fs22-group-14/CAHClient#22
- [x] sopra-fs22-group-14/CAHServer#48
- [x] sopra-fs22-group-14/CAHServer#49
- [x] sopra-fs22-group-14/CAHServer#50
- [x] sopra-fs22-group-14/CAHClient#15
