### ISSUE TITLE
As a user, I want to receive 10 white cards in the beginning of the game in order to properly play the game

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#12]
## Acceptance Criteria:
- [x] As soon as the game starts, the cards should be distributed
- [x] No two players should receive the same card. Every card distributed therefore has to be unique
- [x] The distribution of the cards has to happen randomly (e.g. via shuffling)
- [x] The cards are only visible to the player who received them. The other players should not be able to see them
- [x] It is not necessary to be able to read every card fully at the same time. But there has to be a mechanism (e.g. hovering or clicking) that allows to read the entire content of a card.

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#18
- [x] sopra-fs22-group-14/CAHClient#19
- [x] sopra-fs22-group-14/CAHServer#58
- [x] sopra-fs22-group-14/CAHServer#59
- [x] sopra-fs22-group-14/CAHClient#20
- [x] sopra-fs22-group-14/CAHClient#21
- [x] #95
