### ISSUE TITLE
As a user I want the application to run smoothly so that I enjoy playing the game

### ISSUE THREAD

**Issue by Szymskiii** [sopra-fs22-group-14/server#120]
## Acceptance Criteria:
- [x] All known issues should be fixed

## Development Tasks:
- [x] sopra-fs22-group-14/client#57
- [x] sopra-fs22-group-14/client#58
- [x] sopra-fs22-group-14/server#123
- [x] sopra-fs22-group-14/server#125
- [x] sopra-fs22-group-14/server#127
- [x] sopra-fs22-group-14/client#63
- [x] sopra-fs22-group-14/client#64
- [x] sopra-fs22-group-14/client#65
- [x] sopra-fs22-group-14/client#68
- [x] sopra-fs22-group-14/client#69
- [ ] ...
