### ISSUE TITLE
As a Card Czar, I want to receive a black card in the beginning of a round in order to share it with the other players

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#13]
## Acceptance Criteria:
- [x] After the distribution of the white cards, a Card Czar has to be automatically determined
- [x] The Card Czar has to switch every round in a clockwise manner
- [x] The black card which is received is random
- [x] The black card has to be made visible to all players (f. ex. in the middle of the window)
- [x] The black cards always contain one gap

## Development Tasks:
- [x] sopra-fs22-group-14/CAHServer#62
- [x] sopra-fs22-group-14/CAHClient#23
- [x] sopra-fs22-group-14/CAHServer#64
- [x] sopra-fs22-group-14/CAHServer#65
- [x] sopra-fs22-group-14/CAHClient#24
- [x] sopra-fs22-group-14/CAHClient#25
- [x] #90
