### ISSUE TITLE
As a user (NOT Card Czar), I want to play a white card every single round in order to try and create the funniest combination

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#14]
## Acceptance Criteria:
- [x] The black card is shown to everyone
- [x] The card to be played can be selected
- [x] As soon as the card is selected, a “submit” button will be made clickable
- [x] Clicking the button results in submitting the choice
- [x] After the submission, the played card disappears from the players hand
- [x] The players that have already played are marked in green, the ones that have not yet player are marked in red
- [x] The Card Czar of this round cannot play any card

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#26
- [x] sopra-fs22-group-14/CAHClient#27
- [x] sopra-fs22-group-14/CAHClient#28
- [x] sopra-fs22-group-14/CAHServer#70
- [x] sopra-fs22-group-14/CAHServer#72
