### ISSUE TITLE
As a user, I want to receive new white cards after every round in order to have new cards to choose from

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#16]
## Acceptance Criteria:
- [x] After finishing a round, each player has to receive new white cards
- [x] The amount of white cards equals the amount of cards played in the previous round
- [x] The distribution of the cards has to be random
- [x] Every player therefore always has the same amount of white cards
- [x] After this, a new Card Czar is announced the next round begins

## Development Tasks:
- [x] sopra-fs22-group-14/client#41
- [x] sopra-fs22-group-14/server#96
- [x] sopra-fs22-group-14/server#97
