### ISSUE TITLE
As a game winning user, I want to receive some sort of reward (such as „Game Points”) after the game in order to keep track of the games won

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#17]
## Acceptance Criteria:
- [x] The rounds won are counted round-by-round
- [x] The player with the most rounds won is determined and announced to all players
- [x] The game winning player receives a “Game Point”
- [x] The record of each player is updated after finishing the game

## Development Tasks:
- [x] sopra-fs22-group-14/client#43
- [x] sopra-fs22-group-14/client#44
- [x] sopra-fs22-group-14/server#98
- [x] sopra-fs22-group-14/server#99

**Comment by Szymskiii** [comment]
If the winner of the final round is determined transfer players to End Game screen and GET data regarding the winner.
