### ISSUE TITLE
As a user, I want to be able to pick my favourite card (except mine) that was played every round in order to determine a winner

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#19]
## Acceptance Criteria:
- [x] The cards are not associated to a player, so that bias can be minimized
- [x] Players can select the card combinations (clickable)
- [x] After the selection, the player can submit by pressing a „Submit” button
- [x] After this, white cards are refilled
- [x] Each player’s current number of points is shown during the game - leaderboard

## Development Tasks:
- [x] sopra-fs22-group-14/server#104
- [x] sopra-fs22-group-14/client#48
- [x] sopra-fs22-group-14/client#59
- [x] sopra-fs22-group-14/client#60
