### ISSUE TITLE
As a registered user, I want to log in with my credentials in order to access the platform

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#2]
## Acceptance Criteria:
- [x] The login is successful if an existing username with the correct password is entered
- [x] If an unregistered/unauthorized user tries to login, an error message indicating that the given credentials are invalid and the access is denied is shown
- [x] After a successful login, a token is created and the user is redirected to the lobby
- [x] The token is then used for any further requests to the backend (authentication)

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#5
- [x] sopra-fs22-group-14/CAHServer#31
- [x] #40
- [x] sopra-fs22-group-14/CAHClient#6
