### ISSUE TITLE
As a user, I want to save my funniest card combination in order to share it on my profile

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#21]
## Acceptance Criteria:
- [x] At the end of the game, all played combinations (by the respective player) become visible for each of the players
- [x] Players can tic which of the combinations are supposed to be saved on their user profile. They can then save it via a button click
- [x] Players can only tic a maximum of one combination per game
- [x] Choosing a card combination to be saved, the user profile will be updated

## Development Tasks:
- [x] sopra-fs22-group-14/server#114
- [x] sopra-fs22-group-14/server#115
- [x] sopra-fs22-group-14/client#54
- [x] sopra-fs22-group-14/client#55
