### ISSUE TITLE
As a user, I want card combination to be read by a text-to-speech module in order to make the game more fun and interactive

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#23]
## Acceptance Criteria:
- [x] Every played card can be read out loud as a combination (together with the black card)
- [x] Clicking this button results in the corresponding card combination being read by a text-to-speech module

## Development Tasks:
- [x] sopra-fs22-group-14/server#109
- [x] sopra-fs22-group-14/client#51
- [x] sopra-fs22-group-14/client#52
