### ISSUE TITLE
As a user, I want to see my and other players’ profile including records in order to compare myself to others

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#4]
## Acceptance Criteria:
- [x] A user can see his/her records on the profile page
- [x] Upon accessing the profile page, the records register is shown
- [x] A user can access the profile page of all other users' by clicking onto their username in the user overview
- [x] The profile view includes username and records
- [x] The records consist of: total points earned(community mode), total games won, total rounds won(card czar mode) and funniest card combinations played
- [x] After finishing a game, the records are updated
- [x] All profiles from online players are shown in the user overview
- [x] The data is not lost when restarting the server (persistent)

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#10
- [x] sopra-fs22-group-14/CAHClient#9
- [x] sopra-fs22-group-14/CAHClient#8
- [x] sopra-fs22-group-14/client#61
- [ ] sopra-fs22-group-14/CAHServer#38
- [x] #129
- [x] sopra-fs22-group-14/CAHServer#39
- [x] sopra-fs22-group-14/server#88
