### ISSUE TITLE
As a user, I want to edit my user profile in order to make it more secure

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#5]
## Acceptance Criteria:
- [x] A user can change the password and the username on the profile page
- [x] Before submitting any changes to the username or password, the current password has to be re-entered. If incorrect, the change will be discarded and an error shown
- [x] If the user wants to change his username to an already existing one, an error message pops up
- [x] After the change, the user stays logged in and the new values are saved
- [x] Only his/her own profile can be edited

## Development Tasks:
- [x] sopra-fs22-group-14/client#53
- [x] sopra-fs22-group-14/server#113
- [x] sopra-fs22-group-14/client#71
- [x] sopra-fs22-group-14/server#137
