### ISSUE TITLE
As a Card Czar, I want to choose a winning card combination in order to determine a round winner

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#73]
## Acceptance Criteria:
- [x] Only the Card Czar can select the card combinations (clickable)
- [x] After the selection, the Card Czar can submit his/her choice
- [x] The winner is displayed to all players and a round won is added to the winner
- [x] After this, new white cards are distributed (see US 16)

## Development Tasks:
- [x] sopra-fs22-group-14/CAHServer#78
- [x] sopra-fs22-group-14/CAHServer#80
- [x] sopra-fs22-group-14/CAHClient#31
- [x] sopra-fs22-group-14/CAHClient#32
- [x] sopra-fs22-group-14/CAHClient#33
