### ISSUE TITLE
As a user, I want to create a new game in order to look for other players to play with

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#8]
## Acceptance Criteria:
- [x] In the lobby view, the creation of a new game can be initiated by clicking on a “New Game” button
- [x] The creation of the game includes choosing some basic rules like whether to play with a Card Czar or not, which game edition to play, choosing a name as well as the number of rounds to play.
- [x] As soon as the game is created, the user is redirected to a waiting area and the game appears in the lobby for others to join
- [x] A user should only be able to play in one game at a time

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#11
- [x] sopra-fs22-group-14/CAHClient#12
- [x] sopra-fs22-group-14/CAHServer#43
- [x] sopra-fs22-group-14/CAHServer#44
