### ISSUE TITLE
As a user, I want to join a game that has not yet started in order to start playing

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#9]
## Acceptance Criteria:
- [x] In the lobby, the user has the option of joining a current game out of a list of games, which have not started yet and still have free spots
- [x] On the left side of the lobby, there is a sidebar which links to the lobby, the profile or the user overview
- [x] For each game, the user can see who has already joined and a brief overview of the rules that were chosen
- [x] Once joined and the game has not started yet, the user should be finding himself / herself in a waiting area until the defined number of players have joined
- [x] A user can only join one game

## Development Tasks:
- [x] sopra-fs22-group-14/CAHClient#16
- [x] sopra-fs22-group-14/client#38
- [x] sopra-fs22-group-14/CAHClient#17
- [x] sopra-fs22-group-14/CAHClient#34
- [x] sopra-fs22-group-14/CAHServer#54
- [x] sopra-fs22-group-14/CAHServer#55
