### ISSUE TITLE
As a user, I want to be redirected to the lobby if I or someone else leaves the game in order to keep using the application

### ISSUE THREAD

**Issue by diegobugmann** [sopra-fs22-group-14/server#91]
## Acceptance Criteria:
- [x] A user can see a "Leave" Button while playing the game
- [x] When a user decides to leave the game, all players are notified
- [ ] Leaving is both via the "Leave" button or when closing the browser
- [x] All players are then redirected to the lobby
- [x] The game is deleted and not shown in the lobby

## Development Tasks:
- [x] sopra-fs22-group-14/client#39
- [x] sopra-fs22-group-14/server#133
- [x] sopra-fs22-group-14/server#93
